### ISSUE TITLE
Conflicted Nodes: CustomControlNetWeights [ComfyUI-Advanced-ControlNet], CustomT2IAdapterWeights [ComfyUI-Advanced-ControlNet], LatentKeyframeTiming [ComfyUI-Advanced-ControlNet], LoadImagesFromDirectory [ComfyUI-Advanced-ControlNet], SoftControlNetWeights [ComfyUI-Advanced-ControlNet], SoftT2IAdapterWeights [ComfyUI-Advanced-ControlNet], TimestepKeyframe [ComfyUI-Advanced-ControlNet]

### ISSUE THREAD

**Issue by 108863258** [peteromallet/Steerable-Motion#3]
Conflicted Nodes:
CustomControlNetWeights [ComfyUI-Advanced-ControlNet], CustomT2IAdapterWeights [ComfyUI-Advanced-ControlNet], LatentKeyframeTiming [ComfyUI-Advanced-ControlNet], LoadImagesFromDirectory [ComfyUI-Advanced-ControlNet], SoftControlNetWeights [ComfyUI-Advanced-ControlNet], SoftT2IAdapterWeights [ComfyUI-Advanced-ControlNet], TimestepKeyframe [ComfyUI-Advanced-ControlNet]

**Comment by peteromallet** [comment]
Hi @108863258, apologies for the delay. Wasn't checking Github issues as had never gotten any before. This should be fixed as of last week.
