### ISSUE TITLE
torch.Size

### ISSUE THREAD

**Issue by mischaschaub** [peteromallet/Steerable-Motion#4]
Everything worked perfectly with your lovely workflow, but now I always end up at this same error, even if I take directly your original workflow. Any hint would be helpful! Thanks for your patience...

**_Error occurred when executing IPAdapterApplyEncoded:

Error(s) in loading state_dict for Resampler:
size mismatch for proj_in.weight: copying a param with shape torch.Size([shape torch.Size([768, 1280]) 768, 1280]) from checkpoint, the shape in current model is torch.Size([768, 1024])._**

**Comment by guahunyo** [comment]
I encountered the same problem. How did I solve it?

**Comment by yuancq123** [comment]
> Everything worked perfectly with your lovely workflow, but now I always end up at this same error, even if I take directly your original workflow. Any hint would be helpful! Thanks for your patience...
> 
> **_Error occurred when executing IPAdapterApplyEncoded:
> 
> Error(s) in loading state_dict for Resampler: size mismatch for proj_in.weight: copying a param with shape torch.Size([shape torch.Size([768, 1280]) 768, 1280]) from checkpoint, the shape in current model is torch.Size([768, 1024])._**

i have a same problem. how did u solve it my friend?

**Comment by peteromallet** [comment]
This is 

> > Everything worked perfectly with your lovely workflow, but now I always end up at this same error, even if I take directly your original workflow. Any hint would be helpful! Thanks for your patience...
> > **_Error occurred when executing IPAdapterApplyEncoded:
> > Error(s) in loading state_dict for Resampler: size mismatch for proj_in.weight: copying a param with shape torch.Size([shape torch.Size([768, 1280]) 768, 1280]) from checkpoint, the shape in current model is torch.Size([768, 1024])._**
> 
> i have a same problem. how did u solve it my friend?

This is due to either the models being incorrect or the images being different sizes - woudl recommend you use the suggested models from the left and check the images
