### ISSUE TITLE
TurboVisionXL?

### ISSUE THREAD

**Issue by mischaschaub** [peteromallet/Steerable-Motion#6]
Would it be possible to use turbovisionXL for quicker and perhaps even better results? Would you have any recommendations?

**Comment by peteromallet** [comment]
Yes, will be possible soon - currently SDXL-based models are either limited by frame count (Hotshot) or quality (Animatediff XL) but that'll change soon for both

**Comment by mischaschaub** [comment]
Thanks!

**Comment by peteromallet** [comment]
Thank you - it'll get so much better too as models evolve!

Please join our community if you're interested - a bunch of people experimenting artistically and technically with these models: https://discord.com/invite/JcSA9xmw3K
